server.port: 8081
# Spring Boot configuration
spring:
  zipkin:
    base-url: http://127.0.0.1:9411/

  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payments
    username: postgres
    password: 426105
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
# Connect eureka server
eureka: 
   client:
     serviceUrl:
       defaultZone: http://peer-1-server.com:7001/eureka, http://peer-2-server.com:7002/eureka, http://peer-3-server.com:7003/eureka
     registerWithEureka: true
     fetchRegistry: true

spring.cloud.config.uri: http://localhost:8888/
#spring.cloud.config.enabled: true

my.greeting: "hello from git payment-service to test base-path"


management:
  endpoints:
    web:
      base-path: /payment/actuator
      exposure:
        include: "*"

