server.port: 8081
# Spring Boot configuration
spring:

# Mongo DB props
  data:
      mongodb:
        host: localhost
        port: 27017
        database: ecom


my.greeting: "hello from git product-service to test base-path - revise"


management:
  endpoints:
    web:
      base-path: /product/actuator
      exposure:
        include: "*"
  

