my.greeting: "hello from git product-service - central configuration - control bus7"

spring.application.name: product-service
spring:
  data:
      mongodb:
        host: localhost
        port: 27017
        database: ecom
        
server.port: 0

eureka.instance.instance-id: ${spring.application.name}:${random.uuid}

# Connect eureka server
eureka: 
   client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka
     registerWithEureka: true
     fetchRegistry: true

spring.cloud.bus.id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
spring.cloud.bus.enabled: true
spring.cloud.bus.refresh.enabled: true
spring.cloud.bus.env.enabled: true

management:
  endpoints:
    web:
      base-path: /api/product/actuator
      exposure:
        include: "*"