my.greeting: "hello from git inventory-service - central configuration - control bus3"


spring:
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ecom
    #username: postgres
    #password: 426105
  # JPA properties
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    
server.port: 0
eureka.instance.instance-id: ${spring.application.name}:${random.uuid}

# Connect eureka server
eureka: 
   client:
     serviceUrl:
       defaultZone: http://localhost:8761/eureka
     registerWithEureka: true
     fetchRegistry: true

spring.cloud.bus.id: ${spring.application.name}:${spring.profiles.active}:${random.uuid}
spring.cloud.bus.enabled: true
spring.cloud.bus.refresh.enabled: true
spring.cloud.bus.env.enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"
